spring.application.name=api-service

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/clintrialsync}
spring.datasource.username=${DB_USER:clintrial}
spring.datasource.password=${DB_PASSWORD:clintrial_dev}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true